//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookShop_WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class BOOK
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BOOK()
        {
            this.ORDER_DETAIL = new HashSet<ORDER_DETAIL>();
        }
    
        public int BookID { get; set; }
        [Required(ErrorMessage ="Cannot be blank!")]
        public string BookName { get; set; }
        [Required(ErrorMessage = "Cannot be blank!")]
        public Nullable<decimal> Price { get; set; }
        [Required(ErrorMessage = "Cannot be blank!")]
        public string Decription { get; set; }
        [Required(ErrorMessage = "Cannot be blank!")]
        public Nullable<System.DateTime> UpdateDate { get; set; }

        public string Image { get; set; }
        [Required(ErrorMessage = "Cannot be blank!")]
        public Nullable<int> Quanlity { get; set; }
        [Required(ErrorMessage = "Cannot be blank!")]
        public Nullable<int> CategoryID { get; set; }

        public Nullable<int> PublisherID { get; set; }
    
        public virtual CATEGORY CATEGORY { get; set; }
        public virtual PUBLISHER PUBLISHER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDER_DETAIL> ORDER_DETAIL { get; set; }
    }
}
