//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookShop_WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class CLIENT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CLIENT()
        {
            this.ORDERs = new HashSet<ORDER>();
        }
    
        public int ClientID { get; set; }
        [Required(ErrorMessage = "Cannot be blank!")]
        public string ClientName { get; set; }
        [Required(ErrorMessage = "Cannot be blank!")]
        public string Gender { get; set; }
        [Required(ErrorMessage = "Cannot be blank!")]
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        [Required(ErrorMessage = "Cannot be blank!")]
        public string PhoneNumber { get; set; }
        [Required(ErrorMessage = "Cannot be blank!")]
        public string Address { get; set; }
        [Required(ErrorMessage = "Cannot be blank!")]
        public string Email { get; set; }
        [Required(ErrorMessage = "Cannot be blank!")]
        public string UserName { get; set; }
        [Required(ErrorMessage = "Cannot be blank!")]
        public string Password { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDER> ORDERs { get; set; }
    }
}
