//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookShop_WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class USER
    {
        public int UserID { get; set; }
        [Required(ErrorMessage = "Cannot be blank!")]
        public string Username { get; set; }
        [Required(ErrorMessage = "Cannot be blank!")]
        public string Password { get; set; }
        [Required(ErrorMessage = "Cannot be blank!")]
        public string Fullname { get; set; }
        [Required(ErrorMessage = "Cannot be blank!")]
        public string Email { get; set; }
        public Nullable<int> RoleID { get; set; }
    
        public virtual ROLE ROLE { get; set; }
    }
}
